resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: Github                       
      path: astudentblog/everything
      branches:
        include: master
pipelines: 
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo         
        execution:
          onExecute:
            - echo hello
            - docker ps
            - TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            - curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/public-ipv4
