resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: Github                       
      path: astudentblog/everything
      branches:
        include: master
pipelines: 
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          runtime:
            type: host
        configuration:
          inputResources:
            - name: myGitRepo         
        execution:
          onExecute:
            - echo hello
            - docker ps
            - |
              curl http://169.254.169.254/latest/meta-data/public-ipv4
